### ISSUE TITLE
[QUESTION] fp32_size assert 

### ISSUE THREAD

**Issue by liqing9399** [sail-sg/zero-bubble-pipeline-parallelism#49]
I see that there is an assert statement in the distrib_optimizer.py file. Is there any issue with it? Can I remove it?
` assert fp32_size == 0, "Not supported, because it is rarely used and makes code messy"`
![Uploading zero-bubble.png…]()

**Comment by QPHutu** [comment]
If you're not using `enable_optimizer_post_validation`, then it's safe to just remove it.

Otherwise it will be a bit annoying to deal with it. There are two options
- Delete the code [_release_grad_fp32_from_fp16](https://github.com/sail-sg/zero-bubble-pipeline-parallelism/blob/main/megatron/optimizer/optimizer.py#L630) and [recompute_fp32_grad](https://github.com/sail-sg/zero-bubble-pipeline-parallelism/blob/main/megatron/optimizer/optimizer.py#L657C9-L657C28). It will increase some memory as a result.
- You can refer to [the original code](https://github.com/sail-sg/zero-bubble-pipeline-parallelism/commit/e7cf42043c703531dd640c9332960cef90856f2a), and support it by self.

The reason why we disable it and why we don't provide flags for option 1 is, we really want our code to be clean and without many code branching, and we think it's a rare use case for LLM training.

**Comment by liqing9399** [comment]
thank you!
